name: List down the gcp secrets

on:
    push:
        branches:
            - main

jobs:
    get-secrets:
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
            - name: checkout my code
              uses: actions/checkout@v3
            #Below step is used to authenticate the githuactions with GCP via WIF
            - id: 'auth'
              name: 'Authenticate to my google account'
              uses: 'google-github-actions/auth@v1'
              with:
                token_format: 'access_token'
                workload_identity_provider: 'projects/768624397534/locations/global/workloadIdentityPools/mypoolid1/providers/myproviderid1'
                service_account: 'github-actions-latest@manojproject1-396309.iam.gserviceaccount.com'
            
            - name: 'setup my cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v1'

 #           - id: 'gcloud'
 #             name: 'gcloud'
 #             run: |-
 #               gcloud secrets list

            - name: 'Setup Docker BuildX'
              uses: docker/setup-buildx-action@v1

            - name: 'Build the docker image'
              run: |
                docker buildx create --use
                docker build -t us-east1-docker.pkg.dev/manojproject1-396309/githubaction-testing-cloudrun1/githubactioncodeimage1 .
            
            #For below step read these 2 articles:
            # https://stackoverflow.com/questions/75840164/permission-artifactregistry-repositories-uploadartifacts-denied-on-resource-usin
            # https://cloud.google.com/artifact-registry/docs/docker/pushing-and-pulling#auth
            - name: 'gcloud credential helper'
              run: |
                gcloud auth configure-docker us-east1-docker.pkg.dev

            - name: 'Check the SA roles'
              run: |
                gcloud projects get-iam-policy manojproject1-396309 \
                --flatten="bindings[].members" \
                --format="table(bindings.role,bindings.members)" \
                --filter="bindings.members:serviceAccount:github-actions-latest@manojproject1-396309.iam.gserviceaccount.com"
            
            - name: 'Push the docker image to artifact registry'
              run: |
                docker buildx create --use
                docker push us-east1-docker.pkg.dev/manojproject1-396309/githubaction-testing-cloudrun1/githubactioncodeimage1
                
          
#principal://iam.googleapis.com/projects/768624397534/locations/global/workloadIdentityPools/pool1-manoj/subject/SUBJECT_ATTRIBUTE_VALUE