name: List down the gcp secrets

on:
    push:
        branches:
            - main

jobs:
    get-secrets:
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
            - name: checkout my code
              uses: actions/checkout@v3
             
            - id: 'auth'
              name: 'Authenticate to my google account'
              uses: 'google-github-actions/auth@v1'
              with:
                token_format: 'access_token'
                workload_identity_provider: 'projects/768624397534/locations/global/workloadIdentityPools/githubactions1id/providers/github'
                service_account: 'github-actions-latest@manojproject1-396309.iam.gserviceaccount.com'
            
            - name: 'setup my cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v1'

            - id: 'gcloud'
              name: 'gcloud'
              run: |-
                gcloud secrets list
                
#principal://iam.googleapis.com/projects/768624397534/locations/global/workloadIdentityPools/pool1-manoj/subject/SUBJECT_ATTRIBUTE_VALUE